CREATE TABLE manutencoes_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype TINYINT,
    ativo_id BIGINT,
    tipo VARCHAR(50),
    status VARCHAR(50),
    data_solicitacao DATE,
    data_inicio DATE,
    data_conclusao DATE,
    data_prevista_conclusao DATE,
    descricao_problema VARCHAR(255),
    descricao_servico VARCHAR(255),
    custo_estimado DECIMAL(15, 2),
    custo_real DECIMAL(15, 2),
    fornecedor_id BIGINT,
    solicitante_id BIGINT,
    tecnico_responsavel_id BIGINT,
    tempo_execucao_minutos INTEGER,
    observacoes VARCHAR(255),
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_manutencoes_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (id)
);
